name: Update data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"

jobs:
  execute:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install requests

      - name: Update data
        env:
          PROXY_URL: ${{secrets.PROXY_URL}}
        run: python3 scripts/hole_daten.py

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Update data" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
